PACKAGE_VERSION = "0.1.0"

FEATURE_SCHEMA_VERSION = "1.0"
SCORING_MODEL_VERSION = "1.0"
FINANCIAL_MODEL_VERSION = "1.0"
DECISION_MODEL_VERSION = "1.0"
CONFIDENCE_MODEL_VERSION = "1.0"

CANONICAL_SCHEMA_VERSION = "1.0"