"""SiteScore FAZ 5.2 canonical report-domain projection."""

from .domain import (
    REPORT_PACKAGE_VERSION,
    REPORT_PROJECTION_VERSION,
    REPORT_SCHEMA_VERSION,
    BeautyBusinessInputFacts,
    CanonicalReportFacts,
    CoffeeBusinessInputFacts,
    GymBusinessInputFacts,
    ReportAnalysisFacts,
    ReportBusinessAssumptionsFacts,
    ReportCategoryScoresFacts,
    ReportConfidenceFacts,
    ReportDataQualityFacts,
    ReportDecisionFacts,
    ReportDomainModel,
    ReportFinancialFacts,
    ReportLocationFacts,
    ReportModelVersionsFacts,
    ReportProvenanceFacts,
    ReportRevenueFacts,
    RestaurantBusinessInputFacts,
    RevenueInputFacts,
    build_canonical_report_facts,
    build_report_domain_model,
    require_canonical_report_domain_model,
    require_canonical_report_facts,
)

__version__ = REPORT_PACKAGE_VERSION

__all__ = [
    "__version__",
    "REPORT_PACKAGE_VERSION",
    "REPORT_SCHEMA_VERSION",
    "REPORT_PROJECTION_VERSION",
    "ReportModelVersionsFacts",
    "ReportProvenanceFacts",
    "ReportAnalysisFacts",
    "ReportCategoryScoresFacts",
    "CoffeeBusinessInputFacts",
    "RestaurantBusinessInputFacts",
    "GymBusinessInputFacts",
    "BeautyBusinessInputFacts",
    "RevenueInputFacts",
    "ReportBusinessAssumptionsFacts",
    "ReportLocationFacts",
    "ReportRevenueFacts",
    "ReportFinancialFacts",
    "ReportDecisionFacts",
    "ReportConfidenceFacts",
    "ReportDataQualityFacts",
    "CanonicalReportFacts",
    "ReportDomainModel",
    "build_canonical_report_facts",
    "require_canonical_report_facts",
    "build_report_domain_model",
    "require_canonical_report_domain_model",
]
